-- MySQL Script generated by MySQL Workbench
-- Wed Jun  5 22:13:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Genero Musical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genero Musical` (
  `id_genero_musical` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genero_musical`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_usuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `fecha_de_nacimiento` DATE NOT NULL,
  `id_genero_musical` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_genero_musical`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Usuario_Genero Musical_idx` (`id_genero_musical` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Genero Musical`
    FOREIGN KEY (`id_genero_musical`)
    REFERENCES `mydb`.`Genero Musical` (`id_genero_musical`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Artista` (
  `id_artista` INT NOT NULL,
  `idioma` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_artista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Album` (
  `id_album` INT NOT NULL,
  `fecha_lanzamiento` DATE NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `id_artista` INT NOT NULL,
  PRIMARY KEY (`id_album`, `id_artista`),
  INDEX `fk_Album_Artista1_idx` (`id_artista` ASC) VISIBLE,
  CONSTRAINT `fk_Album_Artista1`
    FOREIGN KEY (`id_artista`)
    REFERENCES `mydb`.`Artista` (`id_artista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Album_genero_musical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Album_genero_musical` (
  `id_album` INT NOT NULL,
  `id_artista` INT NOT NULL,
  `id_genero_musical` INT NOT NULL,
  PRIMARY KEY (`id_album`, `id_artista`, `id_genero_musical`),
  INDEX `fk_Album_has_Genero Musical_Genero Musical1_idx` (`id_genero_musical` ASC) VISIBLE,
  INDEX `fk_Album_has_Genero Musical_Album1_idx` (`id_album` ASC, `id_artista` ASC) VISIBLE,
  CONSTRAINT `fk_Album_has_Genero Musical_Album1`
    FOREIGN KEY (`id_album` , `id_artista`)
    REFERENCES `mydb`.`Album` (`id_album` , `id_artista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Album_has_Genero Musical_Genero Musical1`
    FOREIGN KEY (`id_genero_musical`)
    REFERENCES `mydb`.`Genero Musical` (`id_genero_musical`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Artista_genero_musical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Artista_genero_musical` (
  `id_artista` INT NOT NULL,
  `id_genero_musical` INT NOT NULL,
  PRIMARY KEY (`id_artista`, `id_genero_musical`),
  INDEX `fk_Artista_has_Genero Musical_Genero Musical1_idx` (`id_genero_musical` ASC) VISIBLE,
  INDEX `fk_Artista_has_Genero Musical_Artista1_idx` (`id_artista` ASC) VISIBLE,
  CONSTRAINT `fk_Artista_has_Genero Musical_Artista1`
    FOREIGN KEY (`id_artista`)
    REFERENCES `mydb`.`Artista` (`id_artista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artista_has_Genero Musical_Genero Musical1`
    FOREIGN KEY (`id_genero_musical`)
    REFERENCES `mydb`.`Genero Musical` (`id_genero_musical`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
